services:
  gateway-service:
    build:
      context: ./
      dockerfile: ./services/gateway-service/Dockerfile.dev
    volumes:
      - ./services/gateway-service:/app/services/gateway-service
      - /app/services/gateway-service/node_modules
      
  push-service:
    build:
      context: ./
      dockerfile: ./services/push-service/Dockerfile.dev
    ports:
      - "3003:3003"
    volumes:
      - ./services/push-service:/app/services/push-service
      - /app/services/push-service/node_modules

  email-service:
    build:
      context: ./
      dockerfile: ./services/email-service/Dockerfile.dev
    volumes:
      - ./services/email-service:/app/services/email-service
      - /app/services/email-service/node_modules

  template-service:
    build:
      context: ./
      dockerfile: ./services/template-service/Dockerfile.dev
    volumes:
      - ./services/template-service:/app/services/template-service
      - /app/services/template-service/node_modules

  user-service:
    build:
      context: ./
      dockerfile: ./services/user-service/Dockerfile.dev

    volumes:
      - ./services/user-service:/app/services/user-service
      - /app/services/user-service/node_modules